// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Post struct {
	ID        int32        `json:"id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	Author    string       `json:"author"`
	CreatedAt sql.NullTime `json:"created_at"`
	Slug      string       `json:"slug"`
}
